resource.AddFile("resource/fonts/impact.ttf")
resource.AddFile("resource/fonts/TTimesb.ttf")
resource.AddFile("materials/onxcdmaterial/shop.png")
resource.AddFile("materials/onxcdmaterial/garage.jpg")


surface.CreateFont( "buttonfont", {
	font = "Impact",
	extended = false,
	size = 25,
	weight = 45,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "notifyfont", {
	font = "Amble",
	extended = false,
	size = 30,
	weight = 45,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )
surface.CreateFont( "OCarDealerFont-ID4", {
	font = "Aerial",
	extended = false,
	size = 15,
	weight = 45,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )
surface.CreateFont( "OCarDealerFont-ID5", {
	font = "Vision",
	extended = false,
	size = 22,
	weight = 45,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "OCarDealerFont-ID6", {
	font = "Source Sans Pro",
	extended = false,
	size = 18,
	weight = 45,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )


surface.CreateFont( "TitleFont", {
	font = "Vision Heavy",
	extended = false,
	size = 24,
	weight = 45,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "descfont", {
	font = "Vision Heavy",
	extended = false,
	size = 17,
	weight = 45,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )